"""Emit stage_<slug>.md at the workspace root -- ONLY when a runner produced a
file that git would not show you: a git-ignored keeper that needs ``git add -f``
(typically an Atlas-shipped SAE checkpoint or its matching cache).

Ordinary outputs (tracked-and-modified, or new and not ignored) already appear
in ``git status``, and bulk ignored files stay out of git, so a plan listing them
is redundant. When nothing needs a force-add, no file is written and a stale
stage_<slug>.md from an earlier run is removed, so an old plan is never mistaken
for this run's. Declared-but-missing outputs are printed as warnings.

Classification per declared path:

  tracked-modified : already tracked, changed         -> git status shows it
  new-untracked    : not tracked and not ignored       -> git status shows it
  ignored-small    : git-ignored, size <= --max-mb      -> git add -f  (THE STAGE FILE)
  ignored-large    : git-ignored, size >  --max-mb      -> bulk; stays out of git
  missing          : path does not exist                -> warning

Shell globs are expanded by the caller; pass concrete paths. Non-existent
paths (e.g. an unmatched glob) are reported as missing, not errors.

Usage:
    emit_stage.py --slug=<slug> [options] <path>...
    emit_stage.py --slug=<slug> --shipped-jsonl=<path> [options] [<path>...]
    emit_stage.py -h | --help

Options:
    --slug=<slug>          Runner slug; names the file stage_<slug>.md.
    --shipped-jsonl=<path> A shipped_saes.jsonl manifest (written by
                           export_viz_data.py). Its checkpoints and matching
                           caches are added to the staged set automatically.
    --max-mb=<n>           Force-add size cap in MB [default: 20].
    --out=<path>           Output path [default: auto] (= ./stage_<slug>.md).
    -h --help              Show this help.
"""

import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from docopt import docopt


def _git_ok(args) -> bool:
    """True iff `git <args>` exits 0 (stdout/stderr suppressed)."""
    return subprocess.run(
        ["git", *args], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL
    ).returncode == 0


def classify(path: Path, max_bytes: int) -> str:
    if not path.exists():
        return "missing"
    p = str(path)
    ignored = _git_ok(["check-ignore", "-q", p])
    tracked = _git_ok(["ls-files", "--error-unmatch", p])
    if ignored:
        return "ignored-small" if path.stat().st_size <= max_bytes else "ignored-large"
    if tracked:
        return "tracked-modified"
    return "new-untracked"


def _mb(path: Path) -> float:
    return path.stat().st_size / (1024 * 1024)


def _disp(path: Path) -> str:
    """Repo-relative POSIX path -- git/bash want forward slashes even on Windows."""
    return path.as_posix()


def bucket(paths: list[str], max_mb: float) -> dict[str, list[Path]]:
    """Classify every declared path, de-duplicated in order."""
    max_bytes = int(max_mb * 1024 * 1024)
    buckets: dict[str, list[Path]] = {
        "tracked-modified": [], "new-untracked": [],
        "ignored-small": [], "ignored-large": [], "missing": [],
    }
    seen = set()
    for raw in paths:
        if raw in seen:
            continue
        seen.add(raw)
        buckets[classify(Path(raw), max_bytes)].append(Path(raw))
    return buckets


def build(slug: str, buckets: dict[str, list[Path]]) -> str | None:
    """The stage plan, or None when nothing needs ``git add -f``."""
    add_f = buckets["ignored-small"]
    if not add_f:
        return None
    lines = [f"# Stage plan: {slug}", "",
             "Generated by `scripts/emit_stage.py` because these outputs are git-ignored "
             "but belong in git. Everything else this run produced shows in `git status`.",
             "", "```bash", "git add -f \\"]
    lines += [f"  {_disp(p)} \\" for p in add_f[:-1]] + [f"  {_disp(add_f[-1])}"]
    lines += ["```", "", "| file | size |", "|---|---|"]
    lines += [f"| `{_disp(p)}` | {_mb(p):.1f} MB |" for p in add_f]
    lines.append("")
    return "\n".join(lines)


def paths_from_shipped_jsonl(jsonl_path: Path) -> list[str]:
    """Expand a shipped_saes.jsonl into checkpoint + matching-cache paths.

    The manifest lives at saes/<game>/shipped_saes.jsonl, so the SAE dir is its
    parent and the eval caches are under <parent>/cache/.
    """
    import json

    if not jsonl_path.exists():
        return []
    saes_dir = jsonl_path.parent
    cache_dir = saes_dir / "cache"
    out: list[str] = []
    for line in jsonl_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            rid = json.loads(line)["run_id"]
        except (json.JSONDecodeError, KeyError):
            continue
        out.append(str(saes_dir / f"{rid}.pt"))
        out.extend(str(p) for p in sorted(cache_dir.glob(f"{rid}_matching-*.pt")))
    return out


def main():
    args = docopt(__doc__)
    slug = args["--slug"]
    max_mb = float(args["--max-mb"])
    out = args["--out"]
    out_path = Path(f"stage_{slug}.md") if out in (None, "auto") else Path(out)

    paths = list(args["<path>"])
    if args["--shipped-jsonl"]:
        paths += paths_from_shipped_jsonl(Path(args["--shipped-jsonl"]))

    buckets = bucket(paths, max_mb)
    for p in buckets["missing"]:
        print(f"[emit_stage] WARNING: declared output missing: {_disp(p)}")
    md = build(slug, buckets)
    if md is None:
        if out_path.exists():
            out_path.unlink()        # a stale plan from an earlier run
        n = len(buckets["tracked-modified"]) + len(buckets["new-untracked"])
        print(f"[emit_stage] nothing needs a force-add: no {out_path.name} "
              f"({n} output(s) to commit show in git status)")
        return
    out_path.write_text(md, encoding="utf-8")
    print(f"[emit_stage] wrote {out_path}: {len(buckets['ignored-small'])} file(s) need git add -f")


if __name__ == "__main__":
    main()
