"""Emit stage_<slug>.md at the workspace root: the git-add plan for a runner.

A runner (runners/<slug>.sh) declares the artifacts it produced; this writes a
copy-paste-able ``stage_<slug>.md`` at the repo root so that -- after the runner
finishes on Deep Brain -- you can see at a glance exactly what to commit. It is
meant to always run at the end of a runner (no flag to disable).

Everything runs on Deep Brain and you commit there; nothing bulk is moved to
Speed Mind. So the only question this answers is "which of my outputs go into
git, and do they need -f?". Classification per declared path:

  tracked-modified : already tracked, changed         -> git add
  new-untracked    : not tracked and not ignored       -> git add
  ignored-small    : git-ignored, size <= --max-mb      -> git add -f  (keeper)
  ignored-large    : git-ignored, size >  --max-mb      -> SKIP + warn (bulk;
                     regenerate on demand, do not commit)
  missing          : path does not exist                -> noted, skipped

Shell globs are expanded by the caller; pass concrete paths. Non-existent
paths (e.g. an unmatched glob) are reported as missing, not errors.

Usage:
    emit_stage.py --slug=<slug> [options] <path>...
    emit_stage.py --slug=<slug> --shipped-jsonl=<path> [options] [<path>...]
    emit_stage.py -h | --help

Options:
    --slug=<slug>          Runner slug; names the file stage_<slug>.md.
    --shipped-jsonl=<path> A shipped_saes.jsonl manifest (written by
                           export_viz_data.py). Its checkpoints and matching
                           caches are added to the staged set automatically.
    --max-mb=<n>           Force-add size cap in MB [default: 20].
    --out=<path>           Output path [default: auto] (= ./stage_<slug>.md).
    -h --help              Show this help.
"""

import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from docopt import docopt


def _git_ok(args) -> bool:
    """True iff `git <args>` exits 0 (stdout/stderr suppressed)."""
    return subprocess.run(
        ["git", *args], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL
    ).returncode == 0


def classify(path: Path, max_bytes: int) -> str:
    if not path.exists():
        return "missing"
    p = str(path)
    ignored = _git_ok(["check-ignore", "-q", p])
    tracked = _git_ok(["ls-files", "--error-unmatch", p])
    if ignored:
        return "ignored-small" if path.stat().st_size <= max_bytes else "ignored-large"
    if tracked:
        return "tracked-modified"
    return "new-untracked"


def _mb(path: Path) -> float:
    return path.stat().st_size / (1024 * 1024)


def _disp(path: Path) -> str:
    """Repo-relative POSIX path -- git/bash want forward slashes even on Windows."""
    return path.as_posix()


def build(slug: str, paths: list[str], max_mb: float) -> str:
    max_bytes = int(max_mb * 1024 * 1024)
    buckets: dict[str, list[Path]] = {
        "tracked-modified": [], "new-untracked": [],
        "ignored-small": [], "ignored-large": [], "missing": [],
    }
    # de-dup while preserving order
    seen = set()
    for raw in paths:
        if raw in seen:
            continue
        seen.add(raw)
        buckets[classify(Path(raw), max_bytes)].append(Path(raw))

    add = buckets["tracked-modified"] + buckets["new-untracked"]
    add_f = buckets["ignored-small"]

    lines = [f"# Stage plan: {slug}", ""]
    lines.append("Generated by `scripts/emit_stage.py`. Run these on the machine "
                 "where the pipeline ran (Deep Brain), then commit + push.")
    lines.append("")

    if add or add_f:
        lines.append("## Commit these")
        lines.append("")
        lines.append("```bash")
        if add:
            lines.append("git add \\")
            lines += [f"  {_disp(p)} \\" for p in add[:-1]] + [f"  {_disp(add[-1])}"]
        if add_f:
            lines.append("git add -f \\")
            lines += [f"  {_disp(p)} \\" for p in add_f[:-1]] + [f"  {_disp(add_f[-1])}"]
        lines.append(f'git commit -m "results: {slug}"')
        lines.append("```")
        lines.append("")

    if buckets["ignored-large"]:
        lines.append("## Skipped (bulk; do NOT commit)")
        lines.append("")
        lines.append(f"Git-ignored and over {max_mb:g} MB -- regenerable, keep out "
                     "of git:")
        lines.append("")
        for p in buckets["ignored-large"]:
            lines.append(f"- `{_disp(p)}`  ({_mb(p):.0f} MB)")
        lines.append("")

    if buckets["missing"]:
        lines.append("## Missing (declared but not produced)")
        lines.append("")
        for p in buckets["missing"]:
            lines.append(f"- `{_disp(p)}`")
        lines.append("")

    # compact table
    lines.append("## Summary")
    lines.append("")
    lines.append("| file | action | size |")
    lines.append("|---|---|---|")
    action = {
        "tracked-modified": "git add", "new-untracked": "git add",
        "ignored-small": "git add -f", "ignored-large": "SKIP (bulk)",
        "missing": "MISSING",
    }
    for kind in ("tracked-modified", "new-untracked", "ignored-small",
                 "ignored-large", "missing"):
        for p in buckets[kind]:
            size = f"{_mb(p):.1f} MB" if p.exists() else "-"
            lines.append(f"| `{_disp(p)}` | {action[kind]} | {size} |")
    lines.append("")
    return "\n".join(lines)


def paths_from_shipped_jsonl(jsonl_path: Path) -> list[str]:
    """Expand a shipped_saes.jsonl into checkpoint + matching-cache paths.

    The manifest lives at saes/<game>/shipped_saes.jsonl, so the SAE dir is its
    parent and the eval caches are under <parent>/cache/.
    """
    import json

    if not jsonl_path.exists():
        return []
    saes_dir = jsonl_path.parent
    cache_dir = saes_dir / "cache"
    out: list[str] = []
    for line in jsonl_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            rid = json.loads(line)["run_id"]
        except (json.JSONDecodeError, KeyError):
            continue
        out.append(str(saes_dir / f"{rid}.pt"))
        out.extend(str(p) for p in sorted(cache_dir.glob(f"{rid}_matching-*.pt")))
    return out


def main():
    args = docopt(__doc__)
    slug = args["--slug"]
    max_mb = float(args["--max-mb"])
    out = args["--out"]
    out_path = Path(f"stage_{slug}.md") if out in (None, "auto") else Path(out)

    paths = list(args["<path>"])
    if args["--shipped-jsonl"]:
        paths += paths_from_shipped_jsonl(Path(args["--shipped-jsonl"]))

    md = build(slug, paths, max_mb)
    out_path.write_text(md, encoding="utf-8")
    print(f"[emit_stage] wrote {out_path}")


if __name__ == "__main__":
    main()
